spring.application.name=discovery-service
#Default port number of eureka discovery service which one eureka server try to connect
server.port = 5000
# (false) To disable the automatic search of another eureka discovery-services(in default port 8761)
eureka.client.fetch-registry = false
#(false) To make disable to register its own server details (to register itself it will check default port 8761, if the same discovery service is running in 8761 then it will be able to register)
eureka.client.register-with-eureka = false

#to change hostname(default value is localhost)
eureka.instance.hostname = localhost


