spring.application.name=address-service
server.port=8081
server.servlet.context-path=/address-app/api
# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection
spring.datasource.url=jdbc:postgresql://localhost:5433/microservicedb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
spring.jpa.show-sql=true
# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automatically created afresh for every start of application
spring.jpa.hibernate.ddl-auto=update

# Allows Hibernate to generate SQL optimized for a particular DBMS
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# = EUREKA
# ===============================
#to set url with the zone of eureka server (so that client (employee-service) will register with this server which don't have default url)
eureka.client.service-url.defaultZone = http://localhost:5000/eureka/
#eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

#to set context-path of address-service so that other service able to use.
eureka.instance.metadata-map.configPath = /address-app/api


#to set heartbeat duration to register itself from 30sec (default) to any other time(sec)
#eureka.instance.lease-renewal-interval-in-seconds= 50
#to set duration for when service get removed from eureka server (default is 90)
#eureka.instance.lease-expiration-duration-in-seconds= 100
# ===============================
# = EUREKA's actuator
# ===============================
#related to actuator which is used to show details of application
management.endpoints.web.exposure.include = *

management.info.env.enabled = true
info.app.name = ADDRESS SERVICE
info.app.description = Address service part of a microservices
info.app.version = 1.0.0


